import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { searchAPIRequest } from './searchAPI';

const initialState = {
  results: [],
  lastQuery: '',
  lastPageFetched: 0,
  totalPages: 0,
  status: 'idle'
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchSearch = createAsyncThunk(
  'search/fetchSearch',
  async (args) => {
    const page = args.page ? args.page : 1;
    const response = await searchAPIRequest(args.query, page);
    return response.data;
  }
);

export const fetchNextPage = createAsyncThunk(
  'search/fetchNextPage',
  async (args, thunkAPI) => {
    const state = thunkAPI.getState().search;
    const nextPage = state.lastPageFetched + 1;
    thunkAPI.dispatch(fetchSearch({query: state.lastQuery, page: nextPage}));
  }
);

export const searchSlice = createSlice({
  name: 'search',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchSearch.pending, (state, action) => {
        state.status = 'loading';
        state.lastQuery = action.meta.arg.query;
      })
      .addCase(fetchSearch.fulfilled, (state, action) => {
        state.status = 'idle';
        state.lastPageFetched = action.payload.page;
        state.totalPages = action.payload.total_pages;

        if(action.payload.page === 1){ //If it's the first page that means it's a new search
          state.results = action.payload.results;
        }else{ //if page is > 1 then the request was from infinite scroll
          state.results = state.results.concat(action.payload.results);
        }
      })
      .addCase(fetchSearch.rejected, (state, action) => {
        state.status = 'idle';
        //Store error in state
      });
  },
});

export const { increment, decrement, incrementByAmount } = searchSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectSearchResults = (state) => state.search.results;
export const selectStatus = (state) => state.search.status;
export const selectNoMorePages = (state) => state.search.lastPageFetched === state.search.totalPages;
export const selectNotSearched = (state) => state.search.lastPageFetched === 0;

export default searchSlice.reducer;
